# Generated by Django 4.0.2 on 2025-04-30 16:10

from django.db import migrations, models

import json


def load_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('ingredients', 'Ingredient')
    
    with open('../data/ingredients.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    for item in data:
        Ingredient.objects.get_or_create(
            name=item['name'],
            measurement_unit=item['measurement_unit']
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measurement_unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(load_ingredients),
    ]
