name: Django Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  check-style:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Flake8
      run: |
        cd backend/
        flake8