name: Django Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: tick_db
          POSTGRES_USER: tick_user
          POSTGRES_PASSWORD: tick_password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend/
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run migrations
      env: 
        DATABASE_URL: postgres://tick_user:tick_password@localhost:5433/tick_db
      run: |
        cd backend/
        python manage.py migrate

    - name: Run tests
      env: 
        DATABASE_URL: postgres://tick_user:tick_password@localhost:5433/tick_db
      run: |
        cd backend/
        python manage.py test
    
    - name: Run Flake8
      run: |
        flake8 backend/